services:
  - type: web
    name: twitch-live-assistant
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: TWITCH_CLIENT_ID
        sync: false
      - key: TWITCH_CLIENT_SECRET
        sync: false
      - key: TWITCH_ACCESS_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
